console.log("Hello, World!")
console.log("Welcome to the world of JavaScript!")
console.log("This is a simple JavaScript program.")
console.log("You can use JavaScript to create interactive web pages.")
console.log("JavaScript is a versatile programming language.")
console.log("You can use JavaScript to manipulate the DOM.")
console.log("JavaScript can be used for both front-end and back-end development.")
console.log("With JavaScript, you can create dynamic and responsive web applications.")
console.log("JavaScript is widely used in web development.")
console.log("Learning JavaScript can open up many opportunities in the tech industry.")
